version: '3.2'

services:
  poller:
    build:
      context: .
    container_name: nic_poller
    depends_on:
      - redis
      - elasticsearch
    command: poller --clear-cache --run-forever
    hostname: localhost
    network_mode: host

  redis:
    image: redis
    container_name: nic_redis
    volumes:
      - ./redis_data:/data
    ports:
      - 6379:6379
    hostname: localhost
    network_mode: host

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: nic_elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    hostname: localhost
    network_mode: host